- Cargo.lock
- Cargo.toml
- src/cli/mod.rs
- src/flake_info.rs
This makes FlakeHub flakes behave consistently with GitHub flakes. Unfortunately, this requires a patched tar-rs crate.
> Set the mtime fields in the tarball correctly

- src/release_metadata.rs
The Option/Result logic I use to suss this out is pretty gnarly. I'm open to suggestion on how to clean it up.
> Allow for case-insensitive README names

- src/cli/mod.rs
Setting an env var to nothing (like `ENV=`) will make its value the empty string `""`. This would erroneously print the warning messages about using extra-tags, even when they weren't used.
> Filter out empty strings from labels and tags

- .github/workflows/production-test.yml
- src/mixed-flake.nix
`leaf` is gone, some attributes have been renamed, and there is a new `what` field.
> Update to handle the new schema format

- src/cli/mod.rs
- src/release_metadata.rs
Before, we were reading the README from the current working directory because of a couple things:
* We were reading `entry.file_name()` instead of `entry.path()`, which would be something like `README.md`, instead of a full path to the file. This would lead to reading the `README.md` (if it existed) from the current directory rather than the directory we just searched through.
* We were using the `flake_root` (the root of the git repository) to find the README. This would mean that we would read the `README.md` from wherever this git root was, rather than from the flake itself. Now, we read it from the flake's store path.
> Read README from flake's store path

- src/release_metadata.rs
In #81, we inadvertently appended the subdir to the path which already included the subdir when reading the readme. This causes publishing failures because the directory we expect the readme to exist in likely does not exist:
```
INFO flakehub_push:push_new_release: Preparing release of grahamc/nix-starter-flakes/0.0.0 repository=grahamc/nix-starter-flakes mirror=false upload_name=grahamc/nix-starter-flakes
flake_store_path: "/nix/store/abg459275ipf6x32an2padhjjclx26ip-source/go"
readme_path: "/nix/store/abg459275ipf6x32an2padhjjclx26ip-source/go/go"
```
> Don't re-append the subdir to the store path

- src/cli/mod.rs
This sets the content type header so that `nix flake show "http://localhost:8080/f/DeterminateSystems/nix-installer/0.12.0-rc5.html"` and the like can work.
I tested and this is safe to merge as is, without changing the presign URL.
> Set content type header

- src/cli/mod.rs
- src/graphql/mod.rs
`bearer` is actually not spec conformant: https://datatracker.ietf.org/doc/html/rfc6750#section-2.1
> Prevent "bearer" capitalization mistakes by using the bearer_auth function

- src/cli/mod.rs
Previously, we were issuing a JWT scoped to a service, since we got inspiration from the magic nix cache. Oops! This fixes the audience to be flakehub specific.
> JWT: correct the audience

- src/cli/mod.rs
This will prevent uploading of flakes that need to be re-locked.
> Require flake.lock to be up-to-date if it exists

- action.yaml
- src/cli/mod.rs
- src/flake_info.rs
- src/mixed-flake.nix
This is disabled by default because 1) it might fail (e.g. if the flake uses IFD); and 2) it may be slower (since it requires evaluating the drvPath/outPaths of every flake output).
> Register flake output paths with FlakeHub

- Cargo.lock
- Cargo.toml
- src/cli/instrumentation.rs
- src/cli/mod.rs
- src/error.rs
- src/main.rs
Skip showing the fancy issue report link if the user encounters a known, expected error. (Such as in the future when we stop creating users/orgs on push and invite them to register/login first).
> Offer an improved error experience

- src/cli/mod.rs
- src/error.rs
- src/main.rs
Show a Github Actions error annotation on UNAUTHORIZED responses such that users may see experience an elevated error experience in this expected error case.
> Show github annotation on specific errors.

- Cargo.lock
- Cargo.toml
- src/cli/mod.rs
- src/github/mod.rs
- src/push.rs
- src/release_metadata.rs
This does quite a bit of logic changing to make us not require GitHub Actions for anything but the bearer token.
It is important to note that this (for now) refuses to run if `GITHUB_ACTION` is not set or `--github-token` is not passed. So this doesn't actually remove the need for Github Actions, it just sets the stage for us to add support (similar to #107 and #108).
I believe some of the error messages are still a bit rough... Should give them a better pass before merge.
> Remove non-token dependencies on GitHub Actions

- src/cli/mod.rs
Furthers #109 to decouple the `--github-token` and `is_github_actions` logic. This should make it quite easy to add support for running in other contexts once FlakeHub itself supports those.
> Decouple `--github-token` and `is_github_actions` logic

- src/cli/mod.rs
- src/flakehub_auth_fake.rs
- src/push_context.rs
Update for changes for internal flakehub testing.
I dropped the env var / special handling. We really shouldn't be allowing this to be overriden in actions (and in fact, we already don't have a action-variable for it).
Leaving as draft, it targets the refactor branch and should co-merge with the backend change.
> fake_auth: fix fakeidp jwt usage, take Url for issuer

- .github/workflows/build.yaml
- .prettierignore
- flake.lock
- flake.nix
This PR fixes the macOS builds for `flakehub-push` and also switches out `rust-overlay` in favor of Fenix (mostly just to bring it in line with our other Rust-y flakes).
> Fix macOS build

- .editorconfig
- src/cli/mod.rs
- src/push_context.rs
Gitlab supports subgroups that can nested up to 20 levels, which doesn't work well without our `{owner}/{repo}` schema for flakes. This PR handles subgroup names by converting all slashes past the first one into dashes. Some example conversions:
```ruby
"a/b" => "a/b"
"a/b/c" => "a/b-c"
"a/b/c/d" => "a/b-c-d"
"a/b/c/d/e/f/g/h/i/j/k" => "a/b-c-d-e-f-g-h-i-j-k"
```
There's also a built-in escape hatch from this behavior via `FLAKEHUB_PUSH_DISABLE_SUBGROUPS` or `--disable-subgroups`.
> Enable auto-formatting subgroups in flake names

- src/cli/mod.rs
Oops! An oversight on my part.
> Un-disable subgroup renaming by default

- src/error.rs
- src/main.rs
I'm currently getting this error in Gitlab:
```
Error: 
0: expected value at line 1 column 1
Location:
src/main.rs:125
```
The offending section: https://github.com/DeterminateSystems/flakehub-push/blob/main/src/main.rs#L123-L134
These changes should at least begin to unblock the as-yet-inscrutable issues here: https://gitlab.com/DeterminateSystems/testing/flakehub-push-test-subrepo/-/jobs/7194111999
> Handle non-existent response body

- src/push_context.rs
This still feels a bit messy to me but it fixes the immediate problem, which is that we're currently allowing for upload names of the form `a/b/c` (notice two slashes instead of one), which FlakeHub cannot accept in the `POST` URL.
The major change here is that we no disallow more than one slash in an explicitly supplied upload name even when subgroup renaming is allowed. And if no explicit upload name is provided, we use `{project_owner}/{project_name}` instead of the repository name (we can't use the repository name directly for subgroups).
> Fix upload name handling

- README.md
- docs/development.md
Best to leave this information out of the average reader's hot path.
> Move development docs into separate Markdown file

- docs/development.md
- src/cli/mod.rs
- src/main.rs
- src/push_context.rs
- src/release_metadata.rs
Passing `--dest-dir` will write the tarball and metadata to the specified directory instead of uploading to FlakeHub. This will also avoid getting revision info from GitHub, which is useful when testing against a local repo that hasn't been pushed to GitHub.
> Make it easier to test without GitHub or a local FlakeHub

- .github/workflows/action.yml
- .github/workflows/build.yaml
- .github/workflows/flakehub-publish-rolling.yml
- .github/workflows/production-test.yml
We have FlakeHub Cache, which is not ratelimited, and our release process uses GHA to store the artifacts, so hitting the rate limit means we can't release.
> ci: disable GHA cache

- .github/workflows/build.yaml
The download-artifact and upload-artifact actions need to be the same version.
> ci: fixup upload-artifact action

- README.md
- src/github_actions.rs
- src/main.rs
```yaml
- uses: "DeterminateSystems/flakehub-push@main"
id: push
with:
rolling: true
name: grahamc/test5
visibility: "private"
source-pr: 168
- run: |
echo ${{ steps.push.outputs.flakeref }}
```
> Export the exact flakeref as an output
